/**
 * Static export for Champions 4 Heroes.
 *
 * Renders every public route from a running Umbraco instance into plain HTML
 * plus the wwwroot assets, producing a `dist/` folder that can be hosted free
 * on Netlify, Cloudflare Pages or GitHub Pages.
 *
 * Netlify cannot run Umbraco itself (ephemeral filesystem, no persistent
 * database), so the CMS stays the local editing tool and the export is what
 * gets published.
 *
 *   1. dotnet run
 *   2. node tools/export-static.js [baseUrl] [basePath]
 *
 * basePath is the sub-path the site is served from. Use "/champion-4-heroes"
 * for a project Pages site, or "" when serving from a domain root. Every
 * root-relative URL in the HTML is rewritten to match.
 */

const fs = require('fs');
const path = require('path');

const BASE = (process.argv[2] || 'https://localhost:44369').replace(/\/+$/, '');
const BASE_PATH = (process.argv[3] || '').replace(/\/+$/, '');
const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const WWWROOT = path.join(ROOT, 'wwwroot');

const IGNORE_HREF = /^(#|mailto:|tel:|javascript:)/i;
const HAS_EXTENSION = /\.[a-z0-9]{2,5}$/i;

/**
 * Rewrites root-relative URLs so the site works from a sub-path.
 * "/css/styles.css" with base "/champion-4-heroes" becomes
 * "/champion-4-heroes/css/styles.css". Absolute external URLs are untouched.
 */
function applyBasePath(html) {
  if (!BASE_PATH) return html;
  return html.replace(/(href|src)="\/(?!\/)/g, `$1="${BASE_PATH}/`);
}

function outputFile(route) {
  const clean = route.replace(/^\/+/, '').replace(/\/+$/, '');
  return path.join(DIST, clean, 'index.html');
}

function collectRoutes(html, into) {
  for (const m of html.matchAll(/href="([^"]+)"/g)) {
    const href = m[1];
    if (IGNORE_HREF.test(href)) continue;

    let route = href;
    if (/^https?:\/\//i.test(href)) {
      let u;
      try {
        u = new URL(href);
      } catch {
        continue;
      }
      if (u.host !== new URL(BASE).host) continue;
      route = u.pathname;
    }

    if (!route.startsWith('/')) continue;
    if (route.startsWith('/umbraco')) continue; // back office is not public

    // "/#mission" is the current page, not a new one.
    route = route.split('#')[0];
    if (route === '') route = '/';

    if (HAS_EXTENSION.test(route)) continue; // file, not a page

    into.add(route);
  }
}

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dest = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dest);
    else fs.copyFileSync(src, dest);
  }
}

function countFiles(dir) {
  let n = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    n += entry.isDirectory() ? countFiles(path.join(dir, entry.name)) : 1;
  }
  return n;
}

(async () => {
  console.log(`Exporting from ${BASE} (node ${process.version})`);

  // The app may have just finished booting, so a first refusal is retried
  // rather than treated as fatal.
  let lastError = null;
  for (let attempt = 1; attempt <= 5; attempt++) {
    try {
      const probe = await fetch(BASE + '/');
      if (!probe.ok) throw new Error(`HTTP ${probe.status}`);
      lastError = null;
      break;
    } catch (e) {
      lastError = e;
      console.warn(`  probe attempt ${attempt} failed (${e.message}), retrying`);
      await new Promise((r) => setTimeout(r, 2000));
    }
  }

  if (lastError) {
    console.error(`\nCould not reach ${BASE}. Start the app first:  dotnet run\n(${lastError.message})\n`);
    process.exit(1);
  }

  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST, { recursive: true });

  const done = new Set();
  const queue = ['/'];

  while (queue.length) {
    const route = queue.shift();
    if (done.has(route)) continue;
    done.add(route);

    let html;
    try {
      const res = await fetch(BASE + route, { redirect: 'follow' });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      html = await res.text();
    } catch (e) {
      console.warn(`  skip ${route} (${e.message})`);
      continue;
    }

    const file = outputFile(route);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, applyBasePath(html), 'utf8');
    console.log(`  ${route.padEnd(46)} ${String(html.length).padStart(7)} bytes`);

    const found = new Set();
    collectRoutes(html, found);
    for (const r of found) if (!done.has(r)) queue.push(r);
  }

  copyDir(WWWROOT, DIST);

  fs.writeFileSync(
    path.join(DIST, 'netlify.toml'),
    [
      '# Generated by tools/export-static.js - safe to edit, it is not regenerated by the build.',
      '',
      '[[headers]]',
      '  for = "/*"',
      '  [headers.values]',
      '    X-Content-Type-Options = "nosniff"',
      '    X-Frame-Options = "SAMEORIGIN"',
      '    Referrer-Policy = "strict-origin-when-cross-origin"',
      '',
    ].join('\n'),
    'utf8'
  );

  console.log(`\n${done.size} pages, ${countFiles(DIST)} files total in dist/`);
  console.log(`base path: ${BASE_PATH || '(domain root)'}`);
  console.log('Deploy that folder: netlify deploy --dir=dist --prod');
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
